markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : Manuel Torres - GitHub Pages
production_url : http://ualmtorres.github.com
description: "Througths, flamewars, utilities, tutorials, codes, projects and other things by Carlos Alexandro Becker."
disqus_shortname: ualmtorres
author :
  name : Manuel Torres
  github : ualmtorres
  twitter : ualmtorres
  email: mtorres@ual.es
