pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
exclude: [ Gemfile, Gemfile.lock, gems, _assets, bower_components ]
title : Manuel Torres - GitHub Pages
production_url : http://ualmtorres.github.com
description: "Tutoriales sobre temas variados - Manuel Torres"
disqus_shortname: ualmtorres
author :
  name : Manuel Torres
  github : ualmtorres
  twitter : ualmtorres
  email: mtorres@ual.es
